pipeline{

    agent any     
       
  tools{

        maven "jenkins-mvn"

    }

    environment{

        tomcatWebLocation="\"C:\\Surekha\\Jenkins_training\\apache-tomcat-9.0.55\\apache-tomcat-9.0.55\\webapps\\""

        tomcatBinLocation="\"C:\\Surekha\\Jenkins_training\\apache-tomcat-9.0.55\\apache-tomcat-9.0.55\\bin\\""

        buildLocation="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Tomcat_WebAPP_Pipeline\\mywebapp\\target\\mywebapp.war"

       }
         
         stages{       
                      
             stage('Git Checkout'){
      
                   steps{
        
                       git 'https://github.com/codewithz/dxc-web-app.git'

                    }

             stage('Maven Build'){

                    steps{

                         bat """
                           cd mywebapp
                            mvn clean package
                         """
            }
        }   
     }
         
     post{
        success{bat """
                copy %buildLocation%  %tomcatWebLocation%
                %tomcatBinLocation%\\startup.bat
            """         
               }
    }
  }
}
